version: "3.8"

services:
  springboot:
    container_name: hello-world
    image: springboot:latest
    restart: always
    expose:
      - "80"
    ports:
      - 8000:80
    volumes:
      - springboot-vol:/app
    networks:
      - springboot-net

networks:
  springboot-net:
volumes:
  springboot-vol:
